name: cvresume_web

services:
  frontend:
    container_name: cvresume_web_frontend
    build:
      context: ./
      dockerfile: Dockerfile
    #        image: cvresume_web-frontend
    ports:
      - "3000:3000"
   # expose:
   #   - "81"
    environment:
      - MODE_ENV=production
  nginx:
    container_name: app_nginx_cvresume
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    restart: on-failure
    ports:
      - '81:81'
